#!/bin/sh

/usr/bin/mysql_install_db --user=mysql --defaults-file=/etc/my.cnf

/usr/bin/mysqld_safe --defaults-file=/etc/my.cnf &

sleep 3

mysql -u root -e " \
  SET PASSWORD = PASSWORD('lizhangqu'); \
  UPDATE mysql.user SET password = PASSWORD('lizhangqu') WHERE user = 'root'; \
  DELETE FROM mysql.user WHERE user = ''; \
  GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY 'lizhangqu' WITH GRANT OPTION;"


/usr/bin/mysqladmin -u root -plizhangqu shutdown

